micronaut:
  application:
    name: default
  router:
    static-resources:
      default:
        paths:
          - "classpath:static"
          - "classpath:META-INF/resources/webjars"
netty:
  default:
    allocator:
      max-order: 3
